vivoapp:
    image: gwul/vivo_app_local
vivodb:
    image: gwul/vivo_db
    env_file: env.list
vivotomcat:
    image: gwul/vivo_tomcat
    volumes_from:
        - vivoapp
    ports:
        - "8080:8080"
    links:
        - vivodb:db
    environment:
        - MYDOMAIN
