vivoapp:
    image: gwul/vivo_app_local
vivodb:
    image: gwul/vivo_db
    environment:
        MYSQL_ROOT_PASSWORD: GHr54sfflsE
        MYSQL_DATABASE: vivo
        MYSQL_USER: vivo_user
        MYSQL_PASSWORD: ghE35fkEm4
vivotomcat:
    image: gwul/vivo_tomcat
    volumes_from:
        - vivoapp
    ports:
        - "8080:8080"
    links:
        - vivodb:db
    environment:
        - MYDOMAIN
