vivoapp:
    image: gwul/vivo_app
vivodb:
    image: gwul/vivo_db
    environment:
        - MYSQL_ROOT_PASSWORD: GHr54sfflsETT34
        - MYSQL_DATABASE: vivo
        - MYSQL_USER: vivo_user
        - MYSQL_PASSWORD: ghE35fkEm4dfe3
vivotomcat:
    image: gwul/vivo_tomcat
    volumes_from:
        - vivoapp
    ports:
        - "8080:8080"
    links:
        - vivodb:db
    environment:
        - MYDOMAIN
